config/routes.rb
Rails.application.routes.draw do

  resources :statements do
    member do
      get :toggle_status
    end
  end
  
  devise_for :users
  root to: 'pages#home'
  get 'home', to: 'pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/statement.rb
class Statement < ApplicationRecord
  enum status: {pending: 0, completed: 1}
  validates_presence_of :date
  belongs_to :user

  extend FriendlyId
  friendly_id :user_date, use: [:slugged, :finders]

  def date_title
    date.strftime('%B-%Y')
  end

  def full_name
    user.first_name + '-' + user.last_name
  end

  def user_date
    if date != nil
      full_name + '_' + date_title
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name

  has_many :statements
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:account_update, :last_name])
  end
end

app/controllers/pages_controller.rb
class  PagesController< ApplicationController
  
  def home  
  end

end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  before_action :set_statement, only: [:show, :edit, :update, :destroy, :toggle_status]

  def index
    @statements = Statement.where(user_id: current_user.id)

  end

  def new
    @statement = Statement.new
  end

  def create
    @statement = Statement.new(statement_params)
    @statement.user_id = current_user.id
    if @statement.save
      redirect_to statement_path(@statement)
    else
      render :new
    end
  end

  def show

  end

  def edit
    
  end

  def update
    if @statement.update(statement_params)
      @statement.save
      redirect_to @statement, notice: 'Your statement was edited successfully'
    else
      redirect_to :new, notice: 'Error editing your statement'
    end
  end

  def destroy
    if @statement.destroy
      redirect_to statements_path, notice: 'Your statement was deleted'
    else
      render :show, notice: 'Error deleting your statement'
    end
  end

  def toggle_status
    if @statement.pending?
      @statement.completed!
    elsif @statement.completed?
      @statement.pending!
    end
    redirect_to statements_path, notice: "#{@statement.date.strftime('%B %Y')} has been set to #{@statement.status}"
  end

  private

  def set_statement
    @statement = Statement.friendly.find(params[:id])
  end

  def statement_params
    params.require(:statement).permit(:date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def alerts
    alert = (flash[:alert] || flash[:error] || flash[:notice])

    if alert
      alert_generator alert
    end
  end

  def alert_generator msg
    js add_gritter(msg, sticky: false, time: 1000)
  end
  
end

app/helpers/statements_helper.rb
module StatementsHelper

  def statement_toggler statement
    if statement.pending? 
     link_to 'Pending', toggle_status_statement_path(statement) 
    elsif statement.completed? 
     link_to 'Completed', toggle_status_statement_path(statement) 
   end 
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinancialStatement</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= alerts %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= current_user.inspect %> <br>

<%= link_to 'Statements', statements_path %> <br>

<%= link_to 'logout', destroy_user_session_path, method: :delete %> <br>

app/views/statements/_form.html.erb
<%= form_for @statement do |f| %>

<% if @statement.errors.any? %>
  <% @statement.errors.full_messages.each do |error| %>
    <%= alert_generator error %>
  <% end %>
<% end %>

<%= f.date_field :date %>

<%= f.submit %>

<% end %>

app/views/statements/edit.html.erb
<h1>Edit Statement</h1>

<%= render 'form' %>

app/views/statements/index.html.erb
<h1>Financial Statements</h1>

<%= link_to 'Create New Statement', new_statement_path %> <br>

<% @statements.each do |i| %>
  <%= i.date.strftime('%B %Y') %>
  <%= link_to "Show", statement_path(i) %>
  <%= link_to 'Edit', edit_statement_path(i) %>
  <%= link_to 'Delete', i, method: :delete, data: { confirm: 'Are you sure?'} %>
  <%= statement_toggler(i) %>
  <br>
<% end %>

app/views/statements/new.html.erb
<h1>New Statement</h1>

<%= render 'form' %>

app/views/statements/show.html.erb
<h1><%= @statement.date.strftime('%B %Y') %></h1>
<%= @statement.inspect %> <br>

<%= link_to 'Edit', edit_statement_path %>
<%= link_to "Delete", @statement, method: :delete, data:  {confirm: "Are you sure?"} %>

<%= statement_toggler(@statement) %>